nomoixyz/vulcan

src/Fs.sol

Added docs for the `fs` module.
Closes #35

Fs module documentation

---

src/Events.sol

Adds docs for the events module
Closes #38

Events module documentation

---

src/Env.sol

- Adds docs for the `env` module
- Fixes a naming issue
Closes #39

Env module documentation

---

src/Context.sol

Added docs for the `context` module.
Closes #40

Context module documentation

---

src/Accounts.sol
test/Accounts.t.sol

Stop existing impersonate before impersonating

---

src/Strings.sol

Adds docs for the strings module.
Closes #33

Strings module documentation

---

src/Json.sol

Added docs for the `json` module
Closes #34

Json module documentation

---

src/Fork.sol

chore: add docs for forks module

---

src/Vulcan.sol

Added docs for the `vulcan` module.
Closes #32

Vulcan module documentation

---

README.md
src/Command.sol
src/Fork.sol
src/test.sol
test/Command.t.sol
test/Fork.t.sol

WIP Add basic tests and improve commands

---

test/Context.t.sol

Fix context tests

---

foundry.toml
src/Config.sol
src/Vulcan.sol
src/test.sol
test/Config.t.sol

- Add functions to obtain Rpcs configuration (Closes #76 )

Config module

---

src/Accounts.sol
test/Accounts.t.sol

- Adds `setTokenBalance` functions.

Add `setTokenBalance` to `accounts`

---

docs/src/modules/json.md
test/Json.t.sol

Add test for serializing json object

---

.gitmodules

Update `forge-std` to `v1.5.2`

Update forge std

---

docs/src/modules/json.md
src/Json.sol
test/Json.t.sol

Rename json.serialize to json.set

---

docs/src/reference/modules/json.md

Fix json docs

---

.gitmodules

Update `forge-std` to version `1.6.0`

Update forge std v.1.60

---

docs/src/reference/modules/accounts.md
docs/src/reference/modules/context.md
src/_modules/Accounts.sol
src/_modules/Context.sol

Adds missing functions from `forge-std`

feat: add missing forge-std functions

---

docs/src/reference/modules/commands.md
src/_modules/Commands.sol
src/script.sol
test/_modules/Commands.t.sol

- Adds a function to create an empty command
- Exports the `Command` struct from `script.sol`
Closes #119

feat: improve commands module

---

src/_modules/Accounts.sol
src/_modules/Json.sol

Fixes #134 
Also improves accounts create().

fix: json safe create and improve accounts

---

docs/src/modules/commands.md
docs/src/reference/modules/commands.md

docs: update commands docs

---

src/_modules/Json.sol
test/_modules/Json.t.sol

It's probably ok to merge this. Closes #181

feat!: remove Results from json setters

---

src/_modules/Pointer.sol

feat: add basic types to pointer casting

---

src/_modules/Commands.sol
src/_modules/Error.sol
src/_modules/Fs.sol
src/_modules/Json.sol
src/_modules/Pointer.sol
src/_modules/Result.sol
src/_modules/experimental/Request.sol

chore: improve pointers

---

src/_modules/Semver.sol
src/script.sol
src/test.sol
test/_modules/Semver.t.sol

Adds a semver module.
Closes #203

feat: add semver module

---

.github/workflows/test.yml
Dockerfile
src/_modules/Json.sol
src/_modules/experimental/Request.sol
test/_modules/Json.t.sol
test/_modules/Request.t.sol

- Parses response headers
- Use custom types for request and response headers
- Accept multiple values per header on requests
- Add default headers

Complete request module

---

README.md
docs/src/README.md

Update readme and book example

docs: update examples

---

src/script.sol
src/test.sol

Add missing imports in `script.sol`

fix: add missing imports on script.sol

---

src/_internal/Expect.sol
test/modules/Expect.t.sol

- also fixes the not.toBeAContract condition
- add test cases for toBeAContract

feat: add message to expect utilities

---

docs/src/references/Strings.md
src/_internal/Strings.sol
test/modules/Strings.t.sol

feat: string to json
